Cashflow
we-have-TTA/iCoder pull request #52
Opened 2022-08-31 08:27 UTC by zxcvbnm7548

主要使用套件braintree, aasm
1. 修改user課金狀態，改為團隊課金
2. braintree串金流到paypal
3. aasm狀態機做出當前的狀態(付款成功、 付款失敗 、訂單取消、訂單退款)
4. 修改訂單編號為"ORD20220815XXXXXX(0~9a-zA-Z)"
5. 金鑰密碼需要創建.evn有提供.env.example

2022-08-31 13:19 UTC, zxcvbnm7548 commented
> 主要使用套件braintree, aasm
> 
> 1. 修改user課金狀態，改為團隊課金
> 2. braintree串金流到paypal
> 3. aasm狀態機做出當前的狀態(付款成功、 付款失敗 、訂單取消、訂單退款)
> 4. 修改訂單編號為"ORD20220815XXXXXX(0~9a-zA-Z)"
> 5. 金鑰密碼需要創建.evn有提供.env.example
braintree沙盒登入
https://github.com/we-have-TTA/iCoder/pull/52#issue-1356987893
裏面有三個key複製到.evn

2022-08-31 16:35 UTC, Robeeerto commented on app/views/plans/show.html.erb
> +
空白

2022-08-31 16:35 UTC, Robeeerto commented on app/views/layouts/dashboard.html.erb
> +
空白

2022-08-31 16:36 UTC, Robeeerto commented on app/helpers/orders_helper.rb
> +end
空的 Helper 不要留著

2022-08-31 16:36 UTC, Robeeerto commented on app/helpers/plans_helper.rb
> +end
同上

2022-08-31 16:36 UTC, Robeeerto commented on app/controllers/rooms_controller.rb
> +    params.require(:room).permit(:title, :language, :category, :status).merge(team_id: current_user.team_id)
另一個 PR 有留言過了，可以去看

2022-08-31 16:36 UTC, Robeeerto commented on app/controllers/plans_controller.rb
> +end
這是做什麼用的？

2022-08-31 16:37 UTC, Robeeerto commented on app/controllers/orders_controller.rb
> +  )
private 方法後全部縮排都錯了

2022-09-01 15:12 UTC, noracami requested changes
Conversation 處理完才按 resolve 喔

2022-09-02 09:21 UTC, noracami approved these changes

2022-09-02 09:24 UTC, noracami commented on Gemfile
> +gem 'dotenv-rails', groups: %i[development test]
fixed

2022-09-03 13:29 UTC, oSeanChen approved these changes

2022-09-03 13:29 UTC, Yojijun approved these changes

2022-09-03 13:29 UTC, RexXKao approved these changes

2022-09-03 13:38 UTC, chutienyuan approved these changes

2022-09-03 13:38 UTC, noracami approved these changes

2022-09-03 13:39 UTC, merged